export const todoActionTypes = {
	FETCH_TODOS: 'FETCH_TODOS',
	SET_TODOS: 'SET_TODOS',
	SET_CURRENT_TODO: 'SET_CURRENT_TODO',
	ADD_TODO: 'ADD_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	DELETE_TODO: 'DELETE_TODO',
	SET_ERROR: 'SET_ERROR',
	SET_LOADING: 'SET_LOADING',
};
